# Generated by Django 5.2 on 2026-05-02 07:22

import django.db.models.deletion
import prayer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QiblaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', prayer.models.EncryptedFloatField()),
                ('longitude', prayer.models.EncryptedFloatField()),
                ('direction', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qibla_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer_name', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'prayer_name'],
                'unique_together': {('user', 'date', 'prayer_name')},
            },
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('method', models.IntegerField(choices=[(1, 'University of Islamic Sciences, Karachi'), (2, 'Islamic Society of North America'), (3, 'Muslim World League'), (4, 'Umm Al-Qura University, Makkah'), (5, 'Egyptian General Authority of Survey')], default=1)),
                ('fajr', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('dhuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
