# Generated by Django 5.2 on 2026-05-02 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('fajr', models.CharField(max_length=10)),
                ('dhuhr', models.CharField(max_length=10)),
                ('asr', models.CharField(max_length=10)),
                ('maghrib', models.CharField(max_length=10)),
                ('isha', models.CharField(max_length=10)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'city', 'country')},
            },
        ),
    ]
